### ISSUE TITLE
[136357.895874] usb 2-1: New USB device 

### ISSUE THREAD

**Issue by ritaoo** [pelya/android-keyboard-gadget#108]
Please first read CONTRIBUTING_AND_ISSUE_TEMPLATE.md and do some research about your device! 

I will close your issue without answering if you don't provide me enough information about...
1. your device (DEVICE_CODENAME, KERNEL_VERSION, etc.)
2. what is not working
3. what exactly you would like to have / do.

**Comment by conrad-heimbold** [comment]
?
