### ISSUE TITLE
Building for Samsung Galaxy S3

### ISSUE THREAD

**Issue by the-st0rm** [pelya/android-keyboard-gadget#11]
I am trying to build it for Samsung S3. 
I checked the patch file and I edited/created the required files manually and I did patch the kernel manually. I flashed my kernel using heimdall but I am not sure if it is working. I have Cyangonmod on my device installed actually. 
I am not sure what is wrong. 

Any suggestions??

**Comment by horllste** [comment]
Hello, can you please help me with the installation guide or point me to one, i dont understand this, am using samsunt s3 at&t, cynogenmod 13.0, android 601.

thanks

**Comment by conrad-heimbold** [comment]
@horllste :  Here is a guide on how to build lineageos for Samsung Galaxy S3 International (i9300): 
https://wiki.lineageos.org/devices/i9300/build . The step of patching for HID support has to be done before "brunch i9300". 

The problem seems to have been fixed, therefore closing.
