### ISSUE TITLE
And what with 3.10 kernel?

### ISSUE THREAD

**Issue by Dante383** [pelya/android-keyboard-gadget#115]
I wanted to compile a kernel patch for Galaxy J5 2017 (j5xnlte, MSM8916) but there is no such kernel patch in the repository. What am I supposed to do?

**Comment by conrad-heimbold** [comment]
Please try out 
- generic kernel version [3.04](https://github.com/pelya/android-keyboard-gadget/blob/master/patches/existing_tested/by-generic-kernel-version/generic_kernel_3.04.patch) and [3.18](https://github.com/pelya/android-keyboard-gadget/blob/master/patches/existing_tested/by-generic-kernel-version/generic_kernel_3.18.patch) patches
- [motorola_msm8916_kernel-3.10 patch](https://github.com/pelya/android-keyboard-gadget/blob/master/patches/existing_tested/by-manufacturer-and-soc/motorola__msm8916______kernel_3.10.patch )

**Comment by Dante383** [comment]
@conrad-heimbold motorola_msm8916 was the closest one, but I get these while patching: 

> patching file drivers/usb/gadget/Makefile
> patching file drivers/usb/gadget/android.c
> Hunk #1 FAILED at 61.
> Hunk #2 FAILED at 2899.
> Hunk #3 FAILED at 2979.
> Hunk #4 succeeded at 3392 (offset 54 lines).
> 3 out of 4 hunks FAILED -- saving rejects to file drivers/usb/gadget/android.c.rej
> patching file drivers/usb/gadget/f_hid.c
> patching file drivers/usb/gadget/f_hid.h
> patching file drivers/usb/gadget/f_hid_android_keyboard.c
> patching file drivers/usb/gadget/f_hid_android_mouse.c

I'm using kernel from here: https://github.com/MSM8916-Samsung/android_kernel_samsung_msm8916
What am I doing wrong?

**Comment by conrad-heimbold** [comment]
You are not doing anything wrong. 
Please try to patch the files manually by comparing every $FILE with its $FILE.rej

**Comment by Dante383** [comment]
Okay, compiled. I'm going to flash him now, keep your fingers crossed.

**Comment by conrad-heimbold** [comment]
Wait!

**Comment by Dante383** [comment]
I didn't get a notification from your post, but.. guess what... yes! It works! My first compiled kernel ever, thank you stranger! <3 It feels amazing.

**Comment by conrad-heimbold** [comment]
Congratulations! Could you upload the diff as a patch file? That would be really nice! 
With "diff as a patch file" I mean: 
``
git diff cm-14.1 > samsung_msm8916_kernel-3.10.patch
``

**Comment by Dante383** [comment]
Sure, but are you sure that I have to compare it with cyanogenmod 14.1? Actually I have used kernel from official samsung open source page, so give me some time, I have to figure out how to make a diff out of this

**Comment by conrad-heimbold** [comment]
Ok, then it is more difficult. Could you unpack the src from samsung somewhere else again and compare the two folders with diff -r folder-with-patch folder-without-patch? Thanks!

**Comment by Dante383** [comment]
`diff -r kernel/drivers/gator/gator.mod.c kernel_org/drivers/gator/gator.mod.c
19,153d18
< static const struct modversion_info ____versions[]
< __used
< __attribute__((section("__versions"))) = {
< 	{ 0x9cd374bc, __VMLINUX_SYMBOL_STR(module_layout) },
< 	{ 0x61b7b126, __VMLINUX_SYMBOL_STR(simple_strtoull) },
< 	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
< 	{ 0xfa012fe7, __VMLINUX_SYMBOL_STR(tracepoint_probe_register) },
< 	{ 0x262f20a8, __VMLINUX_SYMBOL_STR(local_clock) },
< 	{ 0xfd002802, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
< 	{ 0xff178f6, __VMLINUX_SYMBOL_STR(__aeabi_idivmod) },
< 	{ 0xfbc74f64, __VMLINUX_SYMBOL_STR(__copy_from_user) },
< 	{ 0x22e1ae6f, __VMLINUX_SYMBOL_STR(up_read) },
< 	{ 0x4b5366cf, __VMLINUX_SYMBOL_STR(down_killable) },
< 	{ 0x528c709d, __VMLINUX_SYMBOL_STR(simple_read_from_buffer) },
< 	{ 0x36d7b11a, __VMLINUX_SYMBOL_STR(of_find_matching_node_and_match) },
< 	{ 0x5fc56a46, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
< 	{ 0xd6ee688f, __VMLINUX_SYMBOL_STR(vmalloc) },
< 	{ 0x67c2fa54, __VMLINUX_SYMBOL_STR(__copy_to_user) },
< 	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
< 	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
< 	{ 0x842d2613, __VMLINUX_SYMBOL_STR(perf_event_release_kernel) },
< 	{ 0x2aceabed, __VMLINUX_SYMBOL_STR(hrtimer_forward) },
< 	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
< 	{ 0xf19e9355, __VMLINUX_SYMBOL_STR(cpu_online_mask) },
< 	{ 0x34184afe, __VMLINUX_SYMBOL_STR(current_kernel_time) },
< 	{ 0x46608fa0, __VMLINUX_SYMBOL_STR(getnstimeofday) },
< 	{ 0x64021802, __VMLINUX_SYMBOL_STR(uncached_logk) },
< 	{ 0xedce55d0, __VMLINUX_SYMBOL_STR(hrtimer_cancel) },
< 	{ 0xbed60566, __VMLINUX_SYMBOL_STR(sub_preempt_count) },
< 	{ 0x20000329, __VMLINUX_SYMBOL_STR(simple_strtoul) },
< 	{ 0x856b28d0, __VMLINUX_SYMBOL_STR(generic_delete_inode) },
< 	{ 0xd3f57a2, __VMLINUX_SYMBOL_STR(_find_next_bit_le) },
< 	{ 0x614fe568, __VMLINUX_SYMBOL_STR(dput) },
< 	{ 0xf087137d, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
< 	{ 0x593a99b, __VMLINUX_SYMBOL_STR(init_timer_key) },
< 	{ 0x9b96369d, __VMLINUX_SYMBOL_STR(mutex_unlock) },
< 	{ 0x81d5e61b, __VMLINUX_SYMBOL_STR(mmput) },
< 	{ 0x999e8297, __VMLINUX_SYMBOL_STR(vfree) },
< 	{ 0xd8f7428a, __VMLINUX_SYMBOL_STR(mount_nodev) },
< 	{ 0x40c7247c, __VMLINUX_SYMBOL_STR(si_meminfo) },
< 	{ 0x7d819333, __VMLINUX_SYMBOL_STR(kthread_create_on_node) },
< 	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
< 	{ 0x7c46233a, __VMLINUX_SYMBOL_STR(cpufreq_quick_get) },
< 	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
< 	{ 0x455293f6, __VMLINUX_SYMBOL_STR(down_read) },
< 	{ 0xfe7c4287, __VMLINUX_SYMBOL_STR(nr_cpu_ids) },
< 	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
< 	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
< 	{ 0xd5f2172f, __VMLINUX_SYMBOL_STR(del_timer_sync) },
< 	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
< 	{ 0x872a0d8a, __VMLINUX_SYMBOL_STR(kill_litter_super) },
< 	{ 0x51d559d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
< 	{ 0xe9bff861, __VMLINUX_SYMBOL_STR(down_trylock) },
< 	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
< 	{ 0x18bd76a4, __VMLINUX_SYMBOL_STR(_raw_spin_trylock) },
< 	{ 0x5f46ea90, __VMLINUX_SYMBOL_STR(d_rehash) },
< 	{ 0x11c9185c, __VMLINUX_SYMBOL_STR(of_iomap) },
< 	{ 0xc917e655, __VMLINUX_SYMBOL_STR(debug_smp_processor_id) },
< 	{ 0x95b9cc84, __VMLINUX_SYMBOL_STR(get_task_mm) },
< 	{ 0x9b2f852b, __VMLINUX_SYMBOL_STR(kunmap) },
< 	{ 0xaafdc258, __VMLINUX_SYMBOL_STR(strcasecmp) },
< 	{ 0x95cb929c, __VMLINUX_SYMBOL_STR(of_find_all_nodes) },
< 	{ 0x9cc4f70a, __VMLINUX_SYMBOL_STR(register_pm_notifier) },
< 	{ 0x84b183ae, __VMLINUX_SYMBOL_STR(strncmp) },
< 	{ 0x73e20c1c, __VMLINUX_SYMBOL_STR(strlcpy) },
< 	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
< 	{ 0xc316eaf7, __VMLINUX_SYMBOL_STR(mutex_lock) },
< 	{ 0x4c6ff041, __VMLINUX_SYMBOL_STR(add_preempt_count) },
< 	{ 0x465757c3, __VMLINUX_SYMBOL_STR(cpu_present_mask) },
< 	{ 0xc2cdbf1, __VMLINUX_SYMBOL_STR(synchronize_sched) },
< 	{ 0x8834396c, __VMLINUX_SYMBOL_STR(mod_timer) },
< 	{ 0x43b0c9c3, __VMLINUX_SYMBOL_STR(preempt_schedule) },
< 	{ 0xe9fac8ac, __VMLINUX_SYMBOL_STR(init_net) },
< 	{ 0x2196324, __VMLINUX_SYMBOL_STR(__aeabi_idiv) },
< 	{ 0x868784cb, __VMLINUX_SYMBOL_STR(__symbol_get) },
< 	{ 0x61651be, __VMLINUX_SYMBOL_STR(strcat) },
< 	{ 0x1fe9f800, __VMLINUX_SYMBOL_STR(unregister_cpu_notifier) },
< 	{ 0x46dffab8, __VMLINUX_SYMBOL_STR(find_vma) },
< 	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
< 	{ 0x34411479, __VMLINUX_SYMBOL_STR(simple_dir_operations) },
< 	{ 0xfd305341, __VMLINUX_SYMBOL_STR(walk_stackframe) },
< 	{ 0x6dd6348d, __VMLINUX_SYMBOL_STR(kmap) },
< 	{ 0x8b43159b, __VMLINUX_SYMBOL_STR(register_cpu_notifier) },
< 	{ 0xf0fdf6cb, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
< 	{ 0xc22c5459, __VMLINUX_SYMBOL_STR(get_user_pages) },
< 	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
< 	{ 0x86a4889a, __VMLINUX_SYMBOL_STR(kmalloc_order_trace) },
< 	{ 0xc2165d85, __VMLINUX_SYMBOL_STR(__arm_iounmap) },
< 	{ 0x2aa0e4fc, __VMLINUX_SYMBOL_STR(strncasecmp) },
< 	{ 0x68bf0a7c, __VMLINUX_SYMBOL_STR(hrtimer_start) },
< 	{ 0xea6e3003, __VMLINUX_SYMBOL_STR(of_find_compatible_node) },
< 	{ 0x3f5eb1fd, __VMLINUX_SYMBOL_STR(wake_up_process) },
< 	{ 0x2c81ec75, __VMLINUX_SYMBOL_STR(__irq_regs) },
< 	{ 0x1e5fd07b, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
< 	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
< 	{ 0x341dbfa3, __VMLINUX_SYMBOL_STR(__per_cpu_offset) },
< 	{ 0x598542b2, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
< 	{ 0xa6c98d1a, __VMLINUX_SYMBOL_STR(register_filesystem) },
< 	{ 0xce46e140, __VMLINUX_SYMBOL_STR(ktime_get_ts) },
< 	{ 0xd85cd67e, __VMLINUX_SYMBOL_STR(__wake_up) },
< 	{ 0xe953b21f, __VMLINUX_SYMBOL_STR(get_next_ino) },
< 	{ 0x68e05d57, __VMLINUX_SYMBOL_STR(getrawmonotonic) },
< 	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
< 	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
< 	{ 0x499cb58c, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
< 	{ 0x3fffd469, __VMLINUX_SYMBOL_STR(hrtimer_init) },
< 	{ 0x4be7fb63, __VMLINUX_SYMBOL_STR(up) },
< 	{ 0x7681946c, __VMLINUX_SYMBOL_STR(unregister_pm_notifier) },
< 	{ 0xa2297b96, __VMLINUX_SYMBOL_STR(__put_task_struct) },
< 	{ 0xb839499, __VMLINUX_SYMBOL_STR(__module_address) },
< 	{ 0xe3926df5, __VMLINUX_SYMBOL_STR(put_page) },
< 	{ 0x52cf508d, __VMLINUX_SYMBOL_STR(d_make_root) },
< 	{ 0x7a1619f4, __VMLINUX_SYMBOL_STR(simple_statfs) },
< 	{ 0x3f675dd9, __VMLINUX_SYMBOL_STR(d_alloc_name) },
< 	{ 0x1cfb04fa, __VMLINUX_SYMBOL_STR(finish_wait) },
< 	{ 0xfb961d14, __VMLINUX_SYMBOL_STR(__arm_ioremap) },
< 	{ 0x6df0b3a6, __VMLINUX_SYMBOL_STR(unregister_filesystem) },
< 	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
< 	{ 0xae286444, __VMLINUX_SYMBOL_STR(perf_event_create_kernel_counter) },
< 	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
< 	{ 0xb2d48a2e, __VMLINUX_SYMBOL_STR(queue_work_on) },
< 	{ 0xe5524eab, __VMLINUX_SYMBOL_STR(of_address_to_resource) },
< 	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
< 	{ 0x2a33078e, __VMLINUX_SYMBOL_STR(new_inode) },
< 	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
< 	{ 0x5541ea93, __VMLINUX_SYMBOL_STR(on_each_cpu) },
< 	{ 0xfaf233aa, __VMLINUX_SYMBOL_STR(simple_dir_inode_operations) },
< 	{ 0xe5d95985, __VMLINUX_SYMBOL_STR(param_ops_ulong) },
< 	{ 0xa8905827, __VMLINUX_SYMBOL_STR(d_instantiate) },
< 	{ 0x6228c21f, __VMLINUX_SYMBOL_STR(smp_call_function_single) },
< 	{ 0xc11bd00f, __VMLINUX_SYMBOL_STR(tracepoint_probe_unregister) },
< 	{ 0xcf24bbc8, __VMLINUX_SYMBOL_STR(dev_get_stats) },
< 	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
< };
< 
160c25
< MODULE_INFO(srcversion, "892DD6F5C58CAC63F2EBC10");
---
> MODULE_INFO(srcversion, "78C8FF4001E68CDD9E4E05A");
diff -r kernel/drivers/usb/gadget/android.c kernel_org/drivers/usb/gadget/android.c
76,78d75
< #include "f_hid.h"
< #include "f_hid_android_keyboard.c"
< #include "f_hid_android_mouse.c"
2907,2942d2903
< static int hid_function_init(struct android_usb_function *f, struct usb_composite_dev *cdev)
< {
< 	return ghid_setup(cdev->gadget, 2);
< }
< 
< static void hid_function_cleanup(struct android_usb_function *f)
< {
< 	ghid_cleanup();
< }
< 
< static int hid_function_bind_config(struct android_usb_function *f, struct usb_configuration *c)
< {
< 	int ret;
< 	printk(KERN_INFO "hid keyboard\n");
< 	ret = hidg_bind_config(c, &ghid_device_android_keyboard, 0);
< 	if (ret) {
< 		pr_info("%s: hid_function_bind_config keyboard failed: %d\n", __func__, ret);
< 		return ret;
< 	}
< 	printk(KERN_INFO "hid mouse\n");
< 	ret = hidg_bind_config(c, &ghid_device_android_mouse, 1);
< 	if (ret) {
< 		pr_info("%s: hid_function_bind_config mouse failed: %d\n", __func__, ret);
< 		return ret;
< 	}
< 	return 0;
< }
< 
< static struct android_usb_function hid_function = {
< 	.name		= "hid",
< 	.init		= hid_function_init,
< 	.cleanup	= hid_function_cleanup,
< 	.bind_config	= hid_function_bind_config,
< };
< 
< 
3100d3060
< 	&hid_function,
3475,3476c3435
< 	/* HID driver always enabled, it's the whole point of this kernel patch */
< 	android_enable_function(dev, conf, "hid");
---
> 
diff -r kernel/drivers/usb/gadget/f_hid.c kernel_org/drivers/usb/gadget/f_hid.c
20d19
< #include <linux/delay.h>
23d21
< #include "f_hid.h"
65,101d62
< /* Hacky device list to fix f_hidg_write being called after device destroyed.
<    It covers only most common race conditions, there will be rare crashes anyway. */
< enum { HACKY_DEVICE_LIST_SIZE = 4 };
< static struct f_hidg *hacky_device_list[HACKY_DEVICE_LIST_SIZE];
< static void hacky_device_list_add(struct f_hidg *hidg)
< {
< 	int i;
< 	for (i = 0; i < HACKY_DEVICE_LIST_SIZE; i++) {
< 		if (!hacky_device_list[i]) {
< 			hacky_device_list[i] = hidg;
< 			return;
< 		}
< 	}
< 	pr_err("%s: too many devices, not adding device %p\n", __func__, hidg);
< }
< static void hacky_device_list_remove(struct f_hidg *hidg)
< {
< 	int i;
< 	for (i = 0; i < HACKY_DEVICE_LIST_SIZE; i++) {
< 		if (hacky_device_list[i] == hidg) {
< 			hacky_device_list[i] = NULL;
< 			return;
< 		}
< 	}
< 	pr_err("%s: cannot find device %p\n", __func__, hidg);
< }
< static int hacky_device_list_check(struct f_hidg *hidg)
< {
< 	int i;
< 	for (i = 0; i < HACKY_DEVICE_LIST_SIZE; i++) {
< 		if (hacky_device_list[i] == hidg) {
< 			return 0;
< 		}
< 	}
< 	return 1;
< }
< 
217,222c178
< 	
< 	if (hacky_device_list_check(hidg)) {
< 		pr_err("%s: trying to read from device %p that was destroyed\n", __func__, hidg);
< 		return -EIO;
< 	}
< 	
---
> 
292,297c248
< 	
< 	if (hacky_device_list_check(hidg)) {
< 		pr_err("%s: trying to write to device %p that was destroyed\n", __func__, hidg);
< 		return -EIO;
< 	}
< 	
---
> 
311,316c262
< 		
< 		if (hacky_device_list_check(hidg)) {
< 			pr_err("%s: trying to write to device %p that was destroyed\n", __func__, hidg);
< 			return -EIO;
< 		}
< 		
---
> 
357,361d302
< 	if (hacky_device_list_check(hidg)) {
< 		pr_err("%s: trying to poll device %p that was destroyed\n", __func__, hidg);
< 		return -EIO;
< 	}
< 
363,368d303
< 	
< 	if (hacky_device_list_check(hidg)) {
< 		pr_err("%s: trying to poll device %p that was destroyed\n", __func__, hidg);
< 		return -EIO;
< 	}
< 	
467,472c402
< 		length = min_t(unsigned, length, 1);
< 		if (hidg->bInterfaceSubClass == USB_INTERFACE_SUBCLASS_BOOT)
< 			((u8 *) req->buf)[0] = 0;	/* Boot protocol */
< 		else
< 			((u8 *) req->buf)[0] = 1;	/* Report protocol */
< 		goto respond;
---
> 		goto stall;
484,491d413
< 		length = 0;
< 		if (hidg->bInterfaceSubClass == USB_INTERFACE_SUBCLASS_BOOT) {
< 			if (value == 0)		/* Boot protocol */
< 				goto respond;
< 		} else {
< 			if (value == 1)		/* Report protocol */
< 				goto respond;
< 		}
641c563
< static int hidg_bind(struct usb_configuration *c, struct usb_function *f)
---
> static int __init hidg_bind(struct usb_configuration *c, struct usb_function *f)
647,648c569
< 	pr_info("%s: creating device %p\n", __func__, hidg);
< 	
---
> 
714,715c635
< 	hacky_device_list_add(hidg);
< 	
---
> 
734,739d653
< 	pr_info("%s: destroying device %p\n", __func__, hidg);
< 	/* This does not cover all race conditions, only most common one */
< 	mutex_lock(&hidg->lock);
< 	hacky_device_list_remove(hidg);
< 	mutex_unlock(&hidg->lock);
< 
746,749d659
< 	/* TODO: calling this function crash kernel,
< 	   not calling this funct ion crash kernel inside f_hidg_write */
< 	/* usb_ep_dequeue(hidg->in_ep, hidg->req); */
< 	
782c692
< int hidg_bind_config(struct usb_configuration *c,
---
> int __init hidg_bind_config(struct usb_configuration *c,
836c746
< int ghid_setup(struct usb_gadget *g, int count)
---
> int __init ghid_setup(struct usb_gadget *g, int count)
diff -r kernel/drivers/usb/gadget/Makefile kernel_org/drivers/usb/gadget/Makefile
70c70
< g_android-y			:= android.o f_hid.o
---
> g_android-y			:= android.o
`

Here it is. Probably something is wrong, but it's getting 12 AM here and with my daily amount of sleep..

**Comment by conrad-heimbold** [comment]
Thank you very much!
