### ISSUE TITLE
What patch should i use

### ISSUE THREAD

**Issue by fatkhur1960** [pelya/android-keyboard-gadget#132]
I have samsung galaxy a3(16) "a3xelte" with kernel version 3.10.xx .. can you help me to build the patch for my device? or you can suggest me what patch should i use from you current patchs? thx

**Comment by conrad-heimbold** [comment]
Did you try this one: 
https://github.com/pelya/android-keyboard-gadget/blob/master/patches/existing_tested/by-manufacturer-and-soc/samsung___apq8084______kernel_3.10.patch ?

**Comment by conrad-heimbold** [comment]
what model name does your galaxy a3 have? SM-A310F , SM-A310F/DS, SM-A310Y, SM-A310M or SM-A3100? Depending on that, you have a Samsung **Exynos 7578** , Qualcomm **Snapdragon 410**  or Samsung **Exynos 7870**  processor. Different processors require different linux versions and different kernel patches. 
Please checkout the wikipedia website: https://en.m.wikipedia.org/wiki/Samsung_Galaxy_A3_%282016%29

**Comment by conrad-heimbold** [comment]
You can find out the model name of your galaxy a3 by going to settings > about phone.

**Comment by fatkhur1960** [comment]
My model name is SM-A310F... i had try this patch https://github.com/pelya/android-keyboard-gadget/blob/master/patches/existing_tested/by-manufacturer-and-soc/samsung___apq8084______kernel_3.10.patch . But i got an error while building proccess

**Comment by conrad-heimbold** [comment]
Patching almost never automatically succeeds. You almost always have to patch manually, by 
1. **comparing** every $FILE with its $FILE.rej ; and 
2. **fixing** every error.

**Comment by bhasiththamis** [comment]
@conrad-heimbold  im having galaxy grand prime model:g530h codename: fortunave3g
Which patch should i use ? It has Snapdragon 410 processor ...pls fimd me the patches for my phone 
Thanks in advance:)
