### ISSUE TITLE
Samsung SM-G531F patch

### ISSUE THREAD

**Issue by Shubzz-02** [pelya/android-keyboard-gadget#142]
My device model is SM-G531F.
codename:- grandprimevelte and kernel version is 3.14.27 
can you suggest me what patch should I use from your current patches?

**Comment by PabloGirol** [comment]
Bump (a bit late) I have a SM-G361F coreprimevelte and its the same version as it is compiled from the same source

**Comment by Shubzz-02** [comment]
Hahaha.. Now that device part are lying somewhere in my gadget box.😂😂😂
