### ISSUE TITLE
71c822b gives error when applying.

### ISSUE THREAD

**Issue by Martinvlba** [pelya/android-keyboard-gadget#176]
1. your device (Beryllium,4.9.216,  Linux/arm64 .)
2. When applying latest version of 4.9 patch i get this error.

---------------------------------------------------
patching file drivers/usb/gadget/function/f_hid.c
patch: **** malformed patch at line 193:  	config_group_init_type_name(&opts->func_inst.group, "", &hid_func_type);
---------------------------------------------------
commit version that gives error is 71c822b
commit version that works when patching 261b661
3. would like it to be fixed. Thanks for reading and have a good day or night.

**Comment by pelya** [comment]
Fixed in 0c75adc8
