### ISSUE TITLE
Suzuran 3.10.84 Patch

### ISSUE THREAD

**Issue by TRKARTAL** [pelya/android-keyboard-gadget#177]
dear @pelya my device:

Suzuran codename (Xperia Z5 Compact)
3.10.84 Kernel Version
I need to patch file for patching Nethunter Kernel:https://github.com/Re4son/android_kernel_sony_msm8994/commits/nethunter-14.1
Google Angler patch is got bootlooping device.

Edit: It seems Google's Angler codenamed device's (nexus 6p, uses same SoC) configuration works on Re4son's NetHunter Sony Xperia Z5 Compact kernel, so it bootlooped due to i changed that CPU GOV from performance to interactive therefore it causes bootloop. 
But i'll try that again for fully ensure.

**Comment by PabloGirol** [comment]
Same but for Xperia Z5, same kernel, different configuration

**Comment by TRKARTAL** [comment]
False positive.
