### ISSUE TITLE
Some Questions...Pls Help

### ISSUE THREAD

**Issue by GetRektBoy724** [pelya/android-keyboard-gadget#186]
### My Device Informations
Device : Xiaomi Redmi 6 Global
Codename : Cereus
Kernel : 4.9.77
ROM : Miui 8.11.8
### What Is Not Working 
I Had Not Try It Yet
### What I Would Like To Do
I want to patch my kernel with this HID patch
I found this on your repository : https://github.com/pelya/android-keyboard-gadget/blob/master/patches/existing_tested/by-generic-kernel-version/generic_kernel_4.9.patch
Is this work for my kernel ?
If its work,how to patch it ?
pls help :)

**Comment by penguin359** [comment]
There is nothing specific to this project in patching a kernel. I would suggest doing a little Googling about how to patch and build a Linux kernel and then look at the Miui project's website for details on how to compile their kernel.

**Comment by GetRektBoy724** [comment]
Ok...thx for the reply @penguin359
