### ISSUE TITLE
need hid patch for 4.4.117 kernel

### ISSUE THREAD

**Issue by MrRob0-X** [pelya/android-keyboard-gadget#188]
**device name**: Samsung A30s sm-a307fn

**my kernel repo**: https://github.com/MrRob0-X/exynos7885-a30s

**issue**

i was faced f_hid.c error: https://ibb.co/GRD3GzM and fix it by edit "read_spinlock to "spinlock"
but still didn't appear hidg* in dev directory

i followed all the steps to run hid function and others in kali docs: https://www.kali.org/docs/nethunter/nethunter-kernel-6-config-5/
![nh-kernel-280-usb-2](https://user-images.githubusercontent.com/35136385/108103268-619ac080-7092-11eb-854f-345635e177c8.png)

i just want to fix this problem to run it into nethunter
was tried everything, from patch / fix f_hid.c and nothing

**Comment by almoza** [comment]
How did you solve the missing hidg devices? I am facing the same issue with another kernel. 

Thank you

**Comment by Amir10122002** [comment]
завершили ?

**Comment by Amir10122002** [comment]
завершили ?

**Comment by Amir10122002** [comment]
завершили ?
