### ISSUE TITLE
Is it tested with Lollipop on N7?

### ISSUE THREAD

**Issue by akrezic1** [pelya/android-keyboard-gadget#19]
Hey, not sure if I should post this in issues, but I need to know is it really working with Lollipop? I'm doing some project for college using this kernel, and I really want to switch to Android 5.0.

**Comment by pelya** [comment]
I've tested it on Nexus 7 2012 with Lollipop, so it should work.

**Comment by akrezic1** [comment]
Thanks for fast reply, can't wait to flash Lollipop!
