### ISSUE TITLE
Hid utility quiet switch? 

### ISSUE THREAD

**Issue by Gemok1980** [pelya/android-keyboard-gadget#38]
Hi 
I've managed through a fair amount of trial and error to write a simple script that reads a series of key presses from a txt file ( basically Ctrl c, Alt tab, ctrl v, next entry)and repeats a few hundred times. 
I put a echo counter in the code but can never see its output as the phone screen is always filled with the possible key entries. 
Is there a quiet switch to stop displaying the keys and only show my echo commands? 
Thanks 
For the very useful utility
Chris

**Comment by pelya** [comment]
I've fixed that, please do git pull.

**Comment by Gemok1980** [comment]
Cool thanks I'll do that. 
Again thanks for the utility its saving me loads of time at work. I set it up last thing and when I come in in the morning its done a couple of thousand for me :)
