### ISSUE TITLE
jfltexx, latest cm12.1, latest alucard kernel

### ISSUE THREAD

**Issue by dvd83i** [pelya/android-keyboard-gadget#40]
Hello. I performed all the steps in the xda forum installing the alucard kernel but when I plug the device to my PC, the USB KEYBOARD app crashes, but if I unplug, the app returns to work. Thank you

**Comment by PentesterGuy** [comment]
See If you have debugging mode enabled :D

**Comment by pelya** [comment]
Could you please collect ADB logs when it crashes?

**Comment by dvd83i** [comment]
Hi! I just formatted the device and reinstalled cm12.1, alucard kernel, gapps and USB keyboard app from playstore; I enabled USB debugging and USB HID STweaks and restart the device; I connected it to PC and start the app. Same problem! When I touch the touchpad box or press any key on the display, it crashes!

**Comment by dvd83i** [comment]
Finally it works fine! I istalled latest usb driver from samsung! TnX! 5 Stars!
