### ISSUE TITLE
USB-Keyboard paste function issues.

### ISSUE THREAD

**Issue by cfrett** [pelya/android-keyboard-gadget#42]
When you paste text such as 'Hello "android', the double quote is not converted to a full character, and instead the input is sent as 'Hello ändroid'

**Comment by pelya** [comment]
Works fine for me.  Are you using any non-English non-QWERTY keyboard
layout? What happens if you press Shift + ' (the button next to Enter) on
your regular keyboard?

**Comment by cfrett** [comment]
"United States-International" keyboard layout in Windows 10. That was it. Using "US" layout works as expected.
