### ISSUE TITLE
how to compile a kernel for my old vodafone 858 smart / Huawei 8160

### ISSUE THREAD

**Issue by Steven1000000** [pelya/android-keyboard-gadget#5]
As a family practice doctor, your app could be useful for getting medical notes from my personal device onto the EMR on a locked corporate network.

I would like to learn how to compile a kernel for my old vodafone 858. Before getting my current phone, I found a youtube video detailing the process to flash CM9 which gave the 858 a new lease on life for a while.

I have read your instructions to launch commands on github from a linux box. I have previously run ubuntu from a CD/DVD but I would like to ask if that is the right idea or not as I am in unfamiliar territory and could use a little help please.

**Comment by conrad-heimbold** [comment]
How to build LineageOS (including the kernel and boot image) for e.g. Motorola Moto G: 
https://wiki.lineageos.org/devices/harpia/build
