### ISSUE TITLE
error patching on sprout device

### ISSUE THREAD

**Issue by nophyan** [pelya/android-keyboard-gadget#56]
Help, patching allways got hunk failed at this line

> 
@@ -1422,6 +1460,7 @@ static struct android_usb_function *supported_functions[] = {
 	&diag_function,
 #endif
 	&rmnet_function,
+	&hid_function,
 	NULL
 };

Try with different patch but got same problem in &hid_function
What should i do?

**Comment by nophyan** [comment]
Fixed with manual patch :) thread clossed

**Comment by pelya** [comment]
Okay.
