### ISSUE TITLE
Kernel for the oneplus3

### ISSUE THREAD

**Issue by nielz010** [pelya/android-keyboard-gadget#60]
Does anyone know if there is already a kernel for the onplus 3 that support this app??

**Comment by gmkbenjamin** [comment]
Have you tried a50ce34d7abab8b5ca71cc4be549a53376a846d7? It should work with OnePlus 3 and even 3T I think.

**Comment by conrad-heimbold** [comment]
> Have you tried a50ce34? It should work with OnePlus 3 and even 3T I think.

No answer from you, therefore closing.
