### ISSUE TITLE
Cyanogenmod 13 Kernel?

### ISSUE THREAD

**Issue by mclucario** [pelya/android-keyboard-gadget#62]
Hey, is the patch you provided for the kernels also usable for Android 6.0.1 kernels? Or is there any way to get this app otherwise running on my current OS?

**Comment by conrad-heimbold** [comment]
> Hey, is the patch you provided for the kernels also usable for Android 6.0.1 kernels?

Depends on a lot of factors, so I need more information from you, please look in ISSUE_TEMPLATE , especially: 
- device_codename
- kernel version
- system-on-chip name
