### ISSUE TITLE
LG v10 keyboard via USB. How do I do this  

### ISSUE THREAD

**Issue by BruceBakken** [pelya/android-keyboard-gadget#70]

**Comment by conrad-heimbold** [comment]
We can't help you if you don't give us enough information. 
1. Find out the **phone codename** of your LG v10. Example: For "Motorola Moto G4 Play", it is "harpia". 
2. Find out the **SoC codename** of your LG v10. Example: For "Motorola Moto G4 Play", it is "MSM8916" by Motorola, so "motorola_msm8916". 

Search in your android settings > about phone , lineageos wiki, lineageos download section, wikipedia. You should be able to find that information there.

**Comment by conrad-heimbold** [comment]
kernel source: https://github.com/Qualcomm-msm/LG_VS990 

http://lmgtfy.com/?q=how+to+compile+linux+kernel
