### ISSUE TITLE
pls help me, kernel for  XIAOMI3TD

### ISSUE THREAD

**Issue by domald** [pelya/android-keyboard-gadget#76]
I want a custom kernel for xiaomi 3 pisces.

kali nethunter   HID cannot use

**Comment by conrad-heimbold** [comment]
If you say "I want", **nobody** will **ever** help you. 
If you say "I am searching for" or "I would like to have", somebody **might** consider helping you.

**Comment by conrad-heimbold** [comment]
- DEVICE_CODENAME: pisces (see http://en.miui.com/thread-252582-1-1.html ) 
- SOC: Nvidia Tegra 4 AP40 (see https://www.devicespecifications.com/en/model/69422983 )
- KERNEL_SOURCE: https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/pisces-kk-oss =>  or https://android.googlesource.com/kernel/tegra/ 

1. Check the Makefile in the kernel src to get the kernel version of your device. 
2. Search for a suitable patch and apply it. 
3. Compile your kernel again with make.
