### ISSUE TITLE
Samsung j-700HXXU

### ISSUE THREAD

**Issue by Crow-1** [pelya/android-keyboard-gadget#77]
Most of people in Egypt and Other countries use this phone please Make Kernel for this mobile
or learn us how to make kernel.

**Comment by conrad-heimbold** [comment]
- kernel source for GT-E700HXXU (Samsung Galaxy E7 Duos): http://opensource.samsung.com/reception/receptionSub.do?method=sub&sub=F&searchValue=E700HXXU 
- how to build lineageos from source (including the kernel) for e.g. Samsung Galaxy S 2 (gt-i9100): https://wiki.lineageos.org/devices/i9100/build . Take out any relevant information you need from this tutorial (learn it)
- compile the kernel from the first link with a suitable patch (check Makefile).    
    - try this one first: https://github.com/pelya/android-keyboard-gadget/blob/master/patches/existing_tested/by-manufacturer-and-soc/motorola__msm8916______kernel_3.10.patch 
    - or these ones (depending on your kernel version): 
        - if 3.1: https://github.com/pelya/android-keyboard-gadget/blob/master/patches/existing_tested/by-generic-kernel-version/generic_kernel_3.01.patch 
        - if 3.4: https://github.com/pelya/android-keyboard-gadget/blob/master/patches/existing_tested/by-generic-kernel-version/generic_kernel_3.04.patch 
        - if 3.18: https://github.com/pelya/android-keyboard-gadget/blob/master/patches/existing_tested/by-generic-kernel-version/generic_kernel_3.18.patch 
-  To apply the patch: execute $ patch -p1 < $FILENAME_OF_PATCH_FILE.patch from the root of your kernel directory. 
- make the kernel afterwards with suitable parameters (check README).
