### ISSUE TITLE
Kernal Patch for 3.10.73

### ISSUE THREAD

**Issue by Arcadianer** [pelya/android-keyboard-gadget#81]
Hi .. i am pretty much a noob when it comes to flashing or compiling kernal stuff :)
Correct me if i am wrong but,
I have a Nexus 5x so i have to compile the kernal for my self.
I have a Kernal Version 3.10.73 but there is no patch for that kernal.
What should i do ?

**Comment by conrad-heimbold** [comment]
- info about Google Nexus 5x (bullhead): https://wiki.lineageos.org/devices/bullhead
- where to get the kernel src: https://android.googlesource.com/device/lge/bullhead-kernel or 
- try this patch: https://github.com/pelya/android-keyboard-gadget/blob/master/patches/existing_tested/by-manufacturer-and-device-codename/htc_______flounder_____kernel_3.10.patch 
- Try out all other patches: the ones before (3.4) and the ones after (3.18). 
- how to compile lineageos (including the kernel and boot): https://wiki.lineageos.org/devices/bullhead/build
