### ISSUE TITLE
How To Check

### ISSUE THREAD

**Issue by doggukan** [pelya/android-keyboard-gadget#95]
i have installed usb gadget enabled kernel but how can i check if it works or not ? there is no hid devices and i cant edit the functions file

**Comment by dhanush-raj** [comment]
Check in the kali nethunter app for hid interfaces. If dev/hidg0 and dev/hidg1 is present or not.
And one more thing your ROM Developer should add the SEPOLICY commits to it. Otherwise your SElinux mode must be set to permissive..

**Comment by dhanush-raj** [comment]
Check in the kali nethunter app for hid interfaces. If dev/hidg0 and dev/hidg1 is present or not.
And one more thing your ROM Developer should add the SEPOLICY commits to it. Otherwise your SElinux mode must be set to permissive..

**Comment by doggukan** [comment]
there is no hidg interfaces

**Comment by dhanush-raj** [comment]
Are you sure @doggukan  that your kernel is patched according to pelya`s guide.
if then set selinux mode to permissive or in terminal app write setenforce 0. And Check once again

**Comment by doggukan** [comment]
setenforce giving error

**Comment by doggukan** [comment]
on kernel changelog and info .there is hid support added and selinux  is permissive i dont why it didnt workd

**Comment by dhanush-raj** [comment]
Is your ROM rooted with magisk or SuperSu

_Sent from my Motorola Moto G4 Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by conrad-heimbold** [comment]
what does logcat report?

**Comment by conrad-heimbold** [comment]
No answer, therefore closing.
