### ISSUE TITLE
Patch boot.img ?

### ISSUE THREAD

**Issue by Wardenfar** [pelya/android-keyboard-gadget#99]
Can i patch the boot.img (MotoG4) because i have try to compile the kernel but i fail

**Comment by conrad-heimbold** [comment]
We can't help you if you don't tell us the exact problem. What was the error message during compiling? 
Did you try to manually patch the source? 
Do you have Moto G4 (athene), Moto G4 Play (harpia), or even Moto G4 Plus? They are all different...
Kernel source for athene is located here: https://github.com/LineageOS/android_kernel_motorola_msm8952 .

**Comment by conrad-heimbold** [comment]
Which kernel is running on your device? 
Go to Android settings > About Phone > kernel version to check. 
If it is 3.1 , 3.4 or 3.18 , try the patch files given in the repo.

**Comment by Wardenfar** [comment]
3.1

**Comment by conrad-heimbold** [comment]
1. Download the src from the link with git: git clone ...
2. Download the patch file. 
3. Go to the root of your kernel src . 
4. Type git apply <patch-file-dir> 

When errors occur, try to fix them manually.

**Comment by Wardenfar** [comment]
Thanks I m going to try

**Comment by conrad-heimbold** [comment]
How to build LineageOS (including the kernel) for Motorola Moto G4: 
https://wiki.lineageos.org/devices/athene/build
